[package]
name = "electrum-client"
version = "0.1.0"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
license = "MIT"
homepage = "https://github.com/chaintope/tapyrus-electrum-client"
repository = "https://github.com/chaintope/tapyrus-electrum-client"
documentation = "https://docs.rs/electrum-client/"
description = "Tapyrus Electrum client library. Supports plaintext, TLS and Onion servers."
keywords = ["tapyrus", "electrum"]
readme = "README.md"
rust-version = "1.63.0"

# loosely based on https://github.com/evgeniy-scherbina/rust-electrumx-client

[lib]
name = "electrum_client"
path = "src/lib.rs"

[dependencies]
log = "^0.4"
tapyrus = { git = "https://github.com/chaintope/rust-tapyrus", branch = "update_on_bitcoin_0.31.x", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }

# Optional dependencies
openssl = { version = "0.10", optional = true }
rustls = { version = "0.23", optional = true }
webpki-roots = { version = "0.25", optional = true }

byteorder = { version = "1.0", optional = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version="0.3.9", features=["winsock2"], optional = true }

[features]
default = ["proxy", "use-rustls"]
minimal = []
debug-calls = []
proxy = ["byteorder", "winapi", "libc"]
use-rustls = ["webpki-roots", "rustls"]
use-openssl = ["openssl"]
